### ISSUE TITLE
使用逻辑

### ISSUE THREAD

**Issue by G-200010** [OrientSama/xView2DOTA_Tools#1]
您好 请问您可以讲解下这里对于Dota和xView两个数据集实现裁剪筛选类别等整体的实现逻辑吗

**Comment by OrientSama** [comment]
1. 首先将xView数据的标签转化成DOTA格式
2. 将xView数据集，DOTA数据集进行分割
3. 然后对分割后的图片进行公共类的提取
4. 提取完成后将标签转化成COCO格式

**Comment by G-200010** [comment]
好的 谢谢 已经在尝试了
