### ISSUE TITLE
具体的步骤

### ISSUE THREAD

**Issue by ZFU123456** [OrientSama/xView2DOTA_Tools#3]
请问，数据处理的过程中具体的执行步骤是是否是一下：
1. 运行xView.py ---将xView转化为dota格式
2. 将xView数据集，DOTA数据集进行分割，是我的疑惑点，具体运行哪个代码，哪些代码是xView和dota数据集进行分割的？
3. 运行 dota_xview.py ---提取公共类
4.  运行DOTA2COCO.py  
还需麻烦您详细解释一下，非常感谢

**Comment by OrientSama** [comment]
关于2，实在dota文件夹里面的[img_split.py](https://github.com/OrientSama/xView2DOTA_Tools/blob/master/dota/split/img_split.py), 然后里面还有一些split_config，需要你根据实际位置设置一下，这个分割文件是mmrotate提供的分割文件

**Comment by OrientSama** [comment]
我又更新了reademe, 你可以看一下

**Comment by ZFU123456** [comment]
好嘞好嘞 非常感谢您！！
